language: clojure
sudo: false
lein: lein

script:
  - lein test-all
  - ./scripts/build
  - nvm install v6.4.0
  - node --version
  - node out/tests.js

branches:
  only:
    - master

jdk:
  - oraclejdk8
  - oraclejdk7

notifications:
  email:
    recipients:
      - niwi@niwi.nz
    on_success: change
    on_failure: change
